Lore page implemented following design specs
evonove/mysthea-app pull request #105
Opened 2019-02-14 11:26 UTC by MaySantucci

Fixed #96

2019-02-14 11:50 UTC, Alien1993 commented on src/qml.qrc
> +        <file>images/lore/image1.jpg</file>
Move these images in a separate qrc.

2019-02-14 11:50 UTC, Alien1993 commented on src/qml/Mysthea/Pages/Lore.qml
> +    import QtQuick 2.0
Remove whitespace

2019-02-14 11:53 UTC, Alien1993 commented on src/qml/Mysthea/Pages/Lore.qml
> +    padding: 20
`bottomPadding` should be 0 too, otherwise text and images are cut before the end of the screen.
Handle it correctly.

2019-02-14 11:53 UTC, silvanocerza requested changes
See comments

2019-02-14 14:47 UTC, Alien1993 commented on src/qml/Mysthea/Pages/LoreModel.qml
> +        width: root.width - padding * 2
This is not necessary.

2019-02-14 14:57 UTC, synasius requested changes
Change usage of Layout attached props

2019-02-14 14:57 UTC, synasius commented on src/qml/Mysthea/Pages/LoreModel.qml
> +        Layout.fillWidth: true
remove Layout attached propes

2019-02-15 09:48 UTC, silvanocerza approved these changes

2019-02-15 09:49 UTC, merged