[WIP] TG-10: Fix style of card detail page.
evonove/mysthea-app pull request #165
Opened 2020-04-01 13:42 UTC by MaySantucci

2020-04-06 08:29 UTC, Psykopear commented
LGTM :+1:
Merge the other PR first and rebase

2020-04-06 08:29 UTC, Psykopear approved these changes

2020-04-09 10:23 UTC, synasius requested changes

2020-04-09 10:23 UTC, synasius commented on src/qml/Mysthea/CardDetail.qml
> +        color: Palette.black
This is not needed because the palette.windows property is set to black in the main.qml

2020-04-09 10:23 UTC, synasius commented on src/models/commandcomboboxmodel.h
> +  Q_INVOKABLE QString iconUrl(const int &command) const;
Use QUrl

2020-04-09 10:23 UTC, synasius commented on src/models/typecomboboxmodel.h
> +  Q_INVOKABLE QString iconUrl(const int &type) const;
Use QUrl

2020-04-09 10:23 UTC, synasius commented on src/style/MystheaUniverse/Pages/CardDetail.qml
> +    property string cardDetailDelegateUrl: ""
type should be `url`

2020-04-09 10:23 UTC, synasius commented on src/style/MystheaUniverse/Pages/CardsReference.qml
> +    property CommandComboBoxModel commandComboBoxModel: null
Add a note about the models and the fact that these are Mysthea models. The plan is to create an abstract base type which can be extended to create specific models for icaion, mysthea and volfyirion.

2020-04-09 10:50 UTC, synasius approved these changes

2020-04-14 12:26 UTC, Psykopear approved these changes

2020-04-14 12:27 UTC, merged