[WIP] Created generic models.
evonove/mysthea-app pull request #177
Opened 2020-04-17 15:24 UTC by MaySantucci

Missing tests.

2020-04-23 14:03 UTC, synasius requested changes

2020-04-23 14:03 UTC, synasius commented on src/models/artworksmodel.cpp
> +    }
This part could be more appropriate if included in the processFile method

2020-04-23 14:03 UTC, synasius commented on src/models/artworksmodel.cpp
> +}
I might be wrong but I remember that you have to call beginResetModel and endResetModel when you manipulate model data.

2020-04-23 14:03 UTC, synasius commented on src/models/artworksmodel.cpp
> +      m_configurationFile = confFile;
there is no reason to keep a `QJsonDocument` in memory after you parsed it

2020-04-23 14:03 UTC, synasius commented on src/models/artworksmodel.h
> +  void componentComplete();
should be marked with override... I guess your compiler is warning you. Do not ignore compiler's warning :eyes:

2020-04-23 14:03 UTC, synasius commented on src/models/artworksmodel.h
> +  QJsonDocument m_configurationFile;
as I told before I think you do not need to keep all the JSON data in memory once you processed the file.

2020-04-23 14:03 UTC, synasius commented on src/models/cardsmodel.cpp
> +  m_commands = commands;
Why don't you use constructor initializers?

2020-04-23 14:03 UTC, synasius commented on src/models/cardsmodel.cpp
> +    return typeText;
leave translate code

2020-04-23 14:03 UTC, synasius commented on src/models/commandcomboboxmodel.cpp
> +    }
the same considerations I made for the card model applies here.

2020-04-23 14:03 UTC, synasius commented on src/models/commandcomboboxmodel.h
> +  QJsonDocument m_configurationFile;
no QJsonDocument

2020-04-27 09:00 UTC, synasius approved these changes

2020-04-27 13:28 UTC, Psykopear requested changes

2020-04-27 13:28 UTC, Psykopear commented on src/models/icaiontypeproxymodel.cpp
> +      emit filterChanged();
Write this before the if block

2020-04-27 13:28 UTC, Psykopear commented on src/models/icaiontypeproxymodel.cpp
> +    emit filterChanged();
Then remove this lines

2020-04-27 13:28 UTC, Psykopear commented on src/models/mystheatypeproxymodel.cpp
> +    emit filterChanged();
Same as above

2020-04-27 13:38 UTC, Psykopear approved these changes

2020-04-27 13:39 UTC, merged